apiVersion: v1
kind: Service
metadata:
  name: rag-agent
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: rag-agent
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
